builds:
- main: cmd/frontman/main.go
  binary: frontman
  goos:
  - windows
  - darwin
  - linux
  goarch:
  - 386
  - amd64
  - arm
  - arm64
  goarm:
  - 7
  # List of combinations of GOOS + GOARCH + GOARM to ignore.
  ignore:
  - goos: darwin
    goarch: 386
  - goos: windows
    goarch: arm
  - goos: darwin
    goarch: arm
  - goos: windows
    goarch: arm64
  - goos: darwin
    goarch: arm64
  env:
  - CGO_ENABLED=0
archive:
  files:
  - README.md
  - example.json
  - example.config.toml
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
nfpm:
  # Default: `{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}`
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

  vendor: cloudradar GmbH
  maintainer: Roman Khafizianov <frontman@cloudradar.io>
  homepage: https://cloudradar.io
  description: Monitoring proxy for agentless monitoring of subnets
  license: MIT

  # Formats to be generated.
  formats:
  - deb
  - rpm

  # Recommend to install root SSL certificates
  recommends:
  - ca-certificates

  # Override default /usr/local/bin destination for binaries
  bindir: /usr/bin

  # Empty folders that should be created and managed by the packager
  # implementation.
  empty_folders:
  - /var/log/frontman
  - /etc/frontman
  - /usr/share/frontman

  # Put example.json
  files:
    "example.json": "/usr/share/doc/frontman/example.json"
    "example.config.toml": "/etc/frontman/example.config.toml"
    "cacert.pem": "/etc/frontman/cacert.pem"

  scripts:
    preinstall: "pkg-scripts/preinstall.sh"
    postinstall: "pkg-scripts/postinstall.sh"
    preremove: "pkg-scripts/preremove.sh"
  overrides:
    deb:
      dependencies:
      - procps
    rpm:
      dependencies:
      - procps-ng